[[redirects]]
from="/about"
to="/"
status=200

[[redirects]]
from="/profile"
to="/"
status=200

[[redirects]]
from="/catalog"
to="/"
status=200

[[redirects]]
from="/order/*"
to="/"
status=200

[[redirects]]
from="/book/*"
to="/"
status=200
